---
- name: Generate kubernetes cert files
  hosts: master
  gather_facts: no
  connection: local
  run_once: true
  vars:
    expire: 3650
  roles:
    - gencert-k8s

- name: Generate etcd cert files
  hosts: etcd
  gather_facts: no
  connection: local
  run_once: true
  vars:
    expire: 3650
  roles:
    - gencert-etcd
