---
- name: Generate etcd cert files
  hosts: init
  gather_facts: no
  connection: local
  run_once: true
  vars:
    cert: etcd
  roles:
    - setvars
    - gencert

- name: Generate kubernetes cert files
  hosts: init
  gather_facts: no
  connection: local
  run_once: true
  vars:
    cert: kubernetes
  roles:
    - setvars
    - gencert
