---
- name: Setup etcd
  hosts: etcd
  remote_user: root
  gather_facts: no
  roles:
    - etcd

- name: Setup kubernetes
  hosts: nodes
  remote_user: root
  gather_facts: yes
  roles:
    - runtime
    - kubelet
    - { role: kube-init, when: "'init' in hostvars[ansible_host]" }
    - { role: calico, when: "calico_enable and 'init' in hostvars[ansible_host]" }
    - { role: kube-join, when: "'init' not in hostvars[ansible_host]" }
