---
- name: Generate internal hosts
  set_fact:
    internal_hosts: "{% set internal_hosts={} %}{% for key, hostvar in hostvars.items() %}{% if 'internal' in hostvar %}{% set x=internal_hosts.__setitem__(hostvar['internal'], hostvar) %}{% else %}{% set x=internal_hosts.__setitem__(key, hostvar) %}{% endif %}{% endfor %}{{ internal_hosts }}"
    internal_host: "{% set hostvar=hostvars[ansible_host] %}{% if 'internal' in hostvar %}{{ hostvar['internal'] }}{% else %}{{ ansible_host }}{% endif %}"
