---
- name: Copy binary
  copy:
    src: "{{ playbook_dir }}/binary/kubernetes/"
    dest: "/usr/local/bin"
    mode: "0755"

- name: Prepare config directory
  file: path="{{ item }}" state=directory mode=0755
  with_items:
    - "/etc/kubernetes"
    - "/etc/systemd/system/kubelet.service.d"

- name: Copy cert
  copy:
    src: "{{ playbook_dir }}/pki"
    dest: "/etc/kubernetes"

- name: Prepare service
  copy:
    src: "kubelet.service"
    dest: "/usr/lib/systemd/system/kubelet.service"

- name: Prepare config
  copy:
    src: "10-kubeadm.conf"
    dest: "/etc/systemd/system/kubelet.service.d/10-kubeadm.conf"

# The kubelet is now restarting every few seconds, as it
# waits in a crashloop for kubeadm to tell it what to do.
- name: Start service
  systemd:
    name: kubelet
    state: restarted
    enabled: yes
    daemon_reload: yes
