---
- name: Prepare groups
  import_tasks: "{{ playbook_dir }}/tasks/group.yml"

- name: Generate config
  template:
    src: "kubeadm-init.yaml"
    dest: "/etc/kubernetes"

- name: Init kubernetes
  shell: kubeadm init --config /etc/kubernetes/kubeadm-init.yaml
