- name: Disable memory swap
  shell: swapoff -a

- name: Set IP local port range
  shell: |
    sed -i '/^net.ipv4.ip_local_port_range*/d' /etc/sysctl.conf
    echo net.ipv4.ip_local_port_range = 32768 60999 >> /etc/sysctl.conf
    sysctl -p

- name: Set max user instance
  shell: |
    echo fs.inotify.max_user_instances = 16384 >> /etc/sysctl.conf
    sysctl -p

- name: Enable net options
  shell: "{{ item }}"
  with_items:
    - modprobe br_netfilter
    - echo 1 > /proc/sys/net/bridge/bridge-nf-call-iptables
    - echo 1 > /proc/sys/net/bridge/bridge-nf-call-ip6tables
    - echo 1 > /proc/sys/net/ipv4/ip_forward
    - sysctl -p

- name: Disable selinux
  ansible.posix.selinux:
    state: disabled

- name: renv for centos
  when: ansible_distribution == "CentOS"
  import_tasks: centos.yml
