- name: Prepare internal hosts
  import_tasks: "{{ playbook_dir }}/tasks/internal_host.yml"

- name: Get etcd nodes
  set_fact:
    etcd_cluster: "{% set etcd_urls=[] %}{% for host in internal_hosts %}{{ etcd_urls.append('etcd{0}=https://{1}:2380'.format(loop.index, host)) }}{% endfor %}{{ etcd_urls | join(',') }}"

- name: Prepare directory
  file: path="/etc/etcd" state=directory mode=0755

- name: Prepare config
  template:
    src: etcd.conf
    dest: /etc/etcd/etcd.conf

- name: Copy cert
  copy:
    src: "{{ playbook_dir }}/pki/etcd"
    dest: /etc/etcd/pki
