---
- name: Prepare cni directory
  file: path="/opt/cni/bin" state=directory mode=0755

- name: Copy cni binary
  copy:
    src: "{{ cni_bin_path }}"
    dest: "/opt/cni/bin/cni.tar.gz"

- name: Prepare cni binary
  shell: "{{ item }}"
  with_items:
    - tar -xzf /opt/cni/bin/cni.tar.gz -C /opt/cni/bin
    - rm /opt/cni/bin/cni.tar.gz
