- name: init
  import_tasks: init.yml

- name: Prepare dirs
  file:
    dest: "{{item}}"
    state: directory
  with_items:
    - /etc/containerd
    - /var/lib/containerd
    - /run/containerd

- name: Copy runc binary
  copy:
    src: "{{ playbook_dir }}/binary/runtime/runc"
    dest: /usr/local/sbin
    mode: "0755"

- name: Copy containerd binary
  copy:
    src: "{{ playbook_dir }}/binary/runtime/{{ item }}"
    dest: /usr/local/bin
    mode: "0755"
  with_items:
    - "containerd/"
    - "crictl"

- name: Generate config
  template:
    src: "containerd.toml"
    dest: /etc/containerd/config.toml

- name: Prepare crictl config
  copy:
    src: "crictl.yaml"
    dest: /etc/crictl.yaml

- name: Prepare service
  copy:
    src: "containerd.service"
    dest: "/usr/lib/systemd/system/containerd.service"

- name: Start service
  systemd:
    name: containerd
    state: restarted
    enabled: yes
    daemon_reload: yes
