---
- name: Generate config
  template:
    src: "kubeadm-join.yaml"
    dest: "/etc/kubernetes"

- name: Join kubernetes
  shell: kubeadm join --config /etc/kubernetes/kubeadm-join.yaml

- name: Prepare kubeconfig
  import_tasks: "{{ playbook_dir }}/tasks/kubeconfig.yml"
